const person = [
  {
    fullName: "Абашникова Ольга Борисовна",
    position: "Специалист по социальной работе",
    address: "Крылатское",
    decree: false,
    img: "AbashnikovaOB.png",
  },
  {
    fullName: "Аверчева Анна Александровна",
    position: "Психолог в социальной сфере",
    address: "Крылатское",
    decree: true,
    img: "0",
  },
  {
    fullName: "Аверьянова Оксана Александровна",
    position: "Специалист по работе с семьей",
    address: "Кунцево",
    decree: false,
    img: "AveryanovaOA.png",
  },
  {
    fullName: "Авраменко Ольга Александровна",
    position: "Специалист по персоналу",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Азизова Ирина Анатольевна",
    position: "Психолог в социальной сфере",
    address: "Тропарево-Никулино",
    decree: false,
    img: "AzizovaIA.png",
  },
  {
    fullName: "Александрова Елена Николаевна",
    position: "Специалист по работе с семьей",
    address: "Дорогомилово",
    decree: false,
    img: "AleksandrovaEN.png",
  },
  {
    fullName: "Антонова Мария Николаевна",
    position: "Специалист по работе с семьей",
    address: "ОССО Сколково",
    decree: false,
    img: "AntonovaMN.png",
  },
  {
    fullName: "Антонова Татьяна Федоровна",
    position: "Специалист по социальной работе",
    address: "Интернациональная",
    decree: false,
    img: "antonovatf.png",
  },
  {
    fullName: "Безбокова Ольга Викторовна",
    position: "Специалист по социальной работе",
    address: "Интернациональная",
    decree: false,
    img: "bezbokovaov.png",
  },
  {
    fullName: "Балашкина Мария Борисовна",
    position: "Юрисконсульт",
    address: "Интернациональная",
    decree: false,
    img: "BalashkinaMB.png",
  },
  {
    fullName: "Бапхоева Татьяна Владимировна",
    position: "Уборщик служебных помещений",
    address: "Тропарево",
    decree: false,
    img: "0",
  },
  {
    fullName: "Баутдинова Юлия Исмаиловна",
    position: "Специалист по работе с семьей",
    address: "Волынская",
    decree: false,
    img: "0",
  },
  {
    fullName: "Банифатьева Алла Тамерлановна",
    position: "Психолог в социальной сфере",
    address: "Раменки",
    decree: false,
    img: "BanifAT.png",
  },
  {
    fullName: "Белан Елена Евгеньевна",
    position: "Заведующий ОКПСД",
    address: "Солнцево",
    decree: false,
    img: "BelanEE.png",
  },
  {
    fullName: "Белов Александр Алексеевич",
    position: "Директор",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Богатеева Любовь Игоревна",
    position: "Психолог в социальной сфере",
    address: "Мичуринский",
    decree: false,
    img: "BogteevaLI.png",
  },
  {
    fullName: "Большакова Елена Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Тропарево",
    decree: false,
    img: "BolshakovaEA.png",
  },
  {
    fullName: "Борзикова Екатерина Юрьевна",
    position: "Заведующий ОКПСД",
    address: "Раменки",
    decree: false,
    img: "BorzikovaEU.png",
  },
  {
    fullName: "Борщева Анастасия Сергеевна",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: false,
    img: "BorschAS.png",
  },
  {
    fullName: "Бочарникова Вера Павловна",
    position: "Специалист по социальной работе",
    address: "Сколково",
    decree: false,
    img: "BocharnikovaVP.png",
  },
  {
    fullName: "Брауэр Андрей Валерьевич",
    position: "Юрисконсульт",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Брауэр Кристина Михайловна",
    position: "Психолог в социальной сфере",
    address: "Тропарево",
    decree: false,
    img: "BrauerKM.png",
  },
  {
    fullName: "Васильева Ирина Александровна",
    position: "Психолог в социальной сфере",
    address: "Кунцево",
    decree: false,
    img: "VasilivaIA.png",
  },
  {
    fullName: "Вахнина Анна Андреевна",
    position: "Медиатор в специализированной сфере",
    address: "Крылатское",
    decree: false,
    img: "VahninaAA.png",
  },
  {
    fullName: "Верясова Светлана Викторовна",
    position: "Специалист по социальной работе",
    address: "Тропарево",
    decree: false,
    img: "VeryasovaSV.png",
  },
  {
    fullName: "Воробьев Юрий Александрович",
    position: "Специалист по работе с семьей",
    address: "Крылатское",
    decree: false,
    img: "VorobyovUA.png",
  },
  {
    fullName: "Герасимова Ольга Анатольевна",
    position: "Заместитель директора",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Герцен Роман Борисович",
    position: "Экономист",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Гончарова Софья Игоревна",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: false,
    img: "GoncharovaSI.png",
  },
  {
    fullName: "Горлова Анна Александровна",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: false,
    img: "GorlovaAA.png",
  },
  {
    fullName: "Господаренко Дарья Дмитриевна",
    position: "Специалист по работе с семьей",
    address: "Тропарево",
    decree: false,
    img: "GospodarenkoDD.png",
  },
  {
    fullName: "Гребенюкова Анастасия Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Интернациональная",
    decree: false,
    img: "GrebenukovaAA.png",
  },
  {
    fullName: "Гришина Елена Николаевна",
    position: "Специалист по работе с семьей",
    address: "Кунцево",
    decree: false,
    img: "GrishinaEN.png",
  },
  {
    fullName: "Гусева Елена Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: false,
    img: "0",
  },
  {
    fullName: "Дворецкая Оксана Игоревна",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: false,
    img: "DvoreckayaOI.png",
  },
  {
    fullName: "Денисова Ирина Сергеевна",
    position: "Специалист по работе с семьей",
    address: "Сколково",
    decree: true,
    img: "0",
  },
  {
    fullName: "Деньга Ксения Сергеевна",
    position: "Психолог в социальной сфере",
    address: "Мичуринский",
    decree: false,
    img: "DengaKS.png",
  },
  {
    fullName: "Деркач Анастасия Сергеевна",
    position: "Специалист по работе с семьей",
    address: "Фили-Давыдково",
    decree: true,
    img: "0",
  },
  {
    fullName: "Дронов Александр Сергеевич",
    position: "Заведующий хозяйством",
    address: "Солнцево",
    decree: false,
    img: "0",
  },
  {
    fullName: "Дронова Надежда Юрьевна",
    position: "Заведующий хозяйством",
    address: "Интернациональная",
    decree: false,
    img: "0",
  },
  {
    fullName: "Дудкина Любовь Геннадьевна",
    position: "Юрисконсульт",
    address: "Дорогомилово",
    decree: false,
    img: "DudkinaLG.png",
  },
  {
    fullName: "Егорова Анна Николаевна",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: false,
    img: "0",
  },
  {
    fullName: "Жихарева Елена Игорьевна",
    position: "Специалист по работе с семьей",
    address: "Крылатское",
    decree: false,
    img: "JiharevaEI.png",
  },
  {
    fullName: "Жомер Владимир Валерьевич",
    position: "Специалист по работе с семьей",
    address: "Сколково",
    decree: false,
    img: "JomerVV.png",
  },
  {
    fullName: "Жуков Александр Валерьевич",
    position: "Специалист по закупкам",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Зарубина Анастасия Анатольевна",
    position: "Специалист по работе с семьей",
    address: "Сколково",
    decree: false,
    img: "ZarubinaAA.png",
  },
  {
    fullName: "Иванин Виктор Сергеевич",
    position: "Психолог в социальной сфере",
    address: "Тропарево",
    decree: false,
    img: "IvaninVS.png",
  },
  {
    fullName: "Иванькова Мария Михайловна",
    position: "Заведующий ОКПСД",
    address: "Сколково",
    decree: false,
    img: "IvankovaMM.png",
  },
  {
    fullName: "Ивашенюк Ольга Петровна",
    position: "Специалист по работе с семьей",
    address: "Кунцево",
    decree: false,
    img: "IvashenukOP.png",
  },
  {
    fullName: "Ильина Ольга Владимировна",
    position: "Психолог в социальной сфере",
    address: "Тропарево",
    decree: true,
    img: "0",
  },
  {
    fullName: "Истомина Татьяна Петровна",
    position: "Заведующий отделением ОКПСД",
    address: "Тропарево",
    decree: false,
    img: "IstominaTP.png",
  },
  {
    fullName: "Истягина Дарья Сергеевна",
    position: "Специалист по работе с семьей",
    address: "Тропарево",
    decree: false,
    img: "IstyaginaDS.png",
  },
  {
    fullName: "Калугин Захар Сергеевич",
    position: "Заведующий ОКПСД",
    address: "Мичуринский",
    decree: false,
    img: "KaluginZS.png",
  },
  {
    fullName: "Канарейкина Наталья Алексеевна",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: false,
    img: "KanareykinaNA.png",
  },
  {
    fullName: "Карпушкина Наталья Владимировна",
    position: "Специалист по работе с семьей",
    address: "Сколково",
    decree: false,
    img: "KarpushkinaNV.png",
  },
  {
    fullName: "Касько Анна Сергеевна",
    position: "Психолог в социальной сфере",
    address: "Сколково",
    decree: false,
    img: "KaskoAS.png",
  },
  {
    fullName: "Кенда Юлия Юрьевна",
    position: "Заместитель директора АУП",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Клевцова Ольга Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Волынская",
    decree: false,
    img: "KlevcovaOA.png",
  },
  {
    fullName: "Клекнер Мария Викторовна",
    position: "Специалист по работе с семьей",
    address: "Сколково",
    decree: false,
    img: "KleknerMV.png",
  },
  {
    fullName: "Клемба Татьяна Станиславовна",
    position: "Специалист по работе с семьей",
    address: "Кутузовский",
    decree: false,
    img: "KlembaTS.png",
  },
  {
    fullName: "Кленова Татьяна Михайловна",
    position: "Специалист по работе с семьей",
    address: "Кунцево",
    decree: false,
    img: "KlenovaTM.png",
  },
  {
    fullName: "Клепцова Анастасия Валентиновна",
    position: "Специалист по работе с семьей",
    address: "Волынская",
    decree: false,
    img: "KleptsovaAV.png",
  },
  {
    fullName: "Клокова Ольга Николаевна",
    position: "Психолог в социальной сфере",
    address: "Тропарево",
    decree: false,
    img: "KlokovaON.png",
  },
  {
    fullName: "Кленье Федор Алексеевич",
    position: "Психолог в социальной сфере",
    address: "Сколково",
    decree: false,
    img: "KleneFA.png",
  },
  {
    fullName: "Колясникова Ирина Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Крылатское",
    decree: false,
    img: "KolyasnikovaIS.png",
  },
  {
    fullName: "Кондратович Наталия Сергеевна",
    position: "Специалист по работе с семьей",
    address: "Волынская",
    decree: false,
    img: "0",
  },
  {
    fullName: "Корниенко Валентина Васильевна",
    position: "Заведующий хозяйством",
    address: "Тропарево",
    decree: false,
    img: "KornienkoVV.png",
  },
  {
    fullName: "Королева Екатерина Александровна",
    position: "Специалист по работе с семьей",
    address: "Интернациональная",
    decree: false,
    img: "KorolevaEA.png",
  },
  {
    fullName: "Костромина Евгения Викторовна",
    position: "Заведующий ОКПСД",
    address: "Интернациональная",
    decree: false,
    img: "KostrominaEV.png",
  },
  {
    fullName: "Кочеров Алексей Евгеньевич",
    position: "Специалист по работе с семьей",
    address: "Мичуринский",
    decree: false,
    img: "KocherovAE.png",
  },
  {
    fullName: "Кривощапова Дарина Борисовна",
    position: "Психолог в социальной сфере",
    address: "Сколково",
    decree: true,
    img: "0",
  },
  {
    fullName: "Кружкова Наталья Андреевна",
    position: "Специалист по работе с семьей",
    address: "Кунцево",
    decree: false,
    img: "0",
  },
  {
    fullName: "Крючкова Анна Николаевна",
    position: "Заведующий отделением ОКПСД",
    address: "Тропарево",
    decree: false,
    img: "KruchkovaVD.png",
  },
  {
    fullName: "Крючкова Виолетта Дмитриевна",
    position: "Медиатор в специализированной сфере",
    address: "Раменки",
    decree: false,
    img: "0",
  },
  {
    fullName: "Курина Александра Павловна",
    position: "Специалист по Охраны труда",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Курмелев Павел Викторович",
    position: "Психолог в социальной сфере",
    address: "Фили-Давыдково",
    decree: false,
    img: "KurmelevPV.png",
  },
  {
    fullName: "Кучеренко Юлия Викторовна",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: false,
    img: "KucherenkoUV.png",
  },
  {
    fullName: "Лаздин Елена Владимировна",
    position: "Специалист по социальной работе",
    address: "Интернациональная",
    decree: false,
    img: "LazdinEV.png",
  },
  {
    fullName: "Ларионова Милянат Гийбатуллаевна",
    position: "Специалист по работе с семьей",
    address: "Фили-Давыдково",
    decree: false,
    img: "LarionovaMG.png",
  },
  {
    fullName: "Лепшина Светлана Александровна",
    position: "Специалист по работе с семьей",
    address: "Дорогомилово",
    decree: true,
    img: "0",
  },
  {
    fullName: "Лобачева Евгения Александровна",
    position: "Заведующий филиалом",
    address: "Крылатское",
    decree: false,
    img: "LobachevaEA.png",
  },
  {
    fullName: "Лопатина Мария Юрьевна",
    position: "Заведующий отделением",
    address: "Фили-Давыдково",
    decree: false,
    img: "LopatinaMU.png",
  },
  {
    fullName: "Лукашова Любовь Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Мичуринский",
    decree: false,
    img: "0",
  },
  {
    fullName: "Макеева Светлана Юрьевна",
    position: "Специалист по работе с семьей",
    address: "Тропарево",
    decree: false,
    img: "MakeevaSU.png",
  },
  {
    fullName: "Мамедова Мирвари Исмаил Кызы",
    position: "Психолог в социальной сфере",
    address: "Тропарево",
    decree: false,
    img: "MamedovaMI.png",
  },
  {
    fullName: "Мещеряков Анатолий Викторович",
    position: "Психолог в социальной сфере",
    address: "Кунцево",
    decree: false,
    img: "MeshAV.png",
  },
  {
    fullName: "Мещерякова Ирина Андреевна",
    position: "Заведующий ОКПСД",
    address: "Крылатское",
    decree: false,
    img: "MeshIA.png",
  },
  {
    fullName: "Митрофанова Наталья Александровна",
    position: "Специалист по работе с семьей",
    address: "Кутузовский",
    decree: false,
    img: "0",
  },
  {
    fullName: "Моисеева Ирина Николаевна",
    position: "Экономист",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Моисеева Мария Константиновна",
    position: "Психолог в социальной сфере",
    address: "Раменки",
    decree: true,
    img: "0",
  },
  {
    fullName: "Мокрушина Ольга Вячеславовна",
    position: "Психолог в социальной сфере",
    address: "Волынская",
    decree: false,
    img: "MokrushinaOV.png",
  },
  {
    fullName: "Морозова Наталья Александровна",
    position: "Психолог в социальной сфере",
    address: "Раменки",
    decree: false,
    img: "0",
  },
  {
    fullName: "Мягков Сергей Иванович",
    position: "Заведующий хозяйством",
    address: "Кунцево",
    decree: false,
    img: "MyagkovSI.png",
  },
  {
    fullName: "Нагорнова Юлия Алексеевна",
    position: "Заведующий ОКПСД",
    address: "Тропарево",
    decree: false,
    img: "NagornovaUA.png",
  },
  {
    fullName: "Наумова Ирина Сергеевна",
    position: "Начальник планово-экономического отдела",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Негодяева Ольга Васильевна",
    position: "Специалист по работе с семьей",
    address: "Тропарево",
    decree: false,
    img: "NegodyaevaOV.png",
  },
  {
    fullName: "Николаева Елена Францевна",
    position: "Специалист по работе с семьей",
    address: "Мичуринский",
    decree: false,
    img: "0",
  },
  {
    fullName: "Никульская Елена Сергеевна",
    position: "Делопроизводитель",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Новосельцева Ирина Юрьевна",
    position: "Специалист по работе с семьей",
    address: "Сколково",
    decree: false,
    img: "NovoIY.png",
  },
  {
    fullName: "Останина Татьяна Александровна",
    position: "Заведующий хозяйством",
    address: "Крылатское",
    decree: false,
    img: "OstaninaTA.png",
  },
  {
    fullName: "Панчохина Екатерина Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Тропарево",
    decree: false,
    img: "PanchohinaEA.png",
  },
  {
    fullName: "Папакин Андрей Геннадиевич",
    position: "Юрисконсульт",
    address: "Кунцево",
    decree: false,
    img: "PapakinAG.png",
  },
  {
    fullName: "Пашкова Раиса Ивановна",
    position: "Психолог в социальной сфере",
    address: "Тропарево",
    decree: false,
    img: "PashkovaRI.png",
  },
  {
    fullName: "Перфилова Ольга Владимировна",
    position: "Уборщик служебных помещений",
    address: "Тропарево",
    decree: false,
    img: "0",
  },
  {
    fullName: "Подгорная Наталья Теодоровна",
    position: "Специалист по социальной работе",
    address: "Волынская",
    decree: false,
    img: "PodgornayaNT.png",
  },
  {
    fullName: "Полковников Николай Васильевич",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: false,
    img: "PolkovnikovNV.png",
  },
  {
    fullName: "Понина Ольга Иликбаевна",
    position: "Специалист по социальной работе",
    address: "Волынская",
    decree: false,
    img: "poninaoi.png",
  },
  {
    fullName: "Поп Ульяна Александровна",
    position: "Специалист по работе с семьей",
    address: "Крылатское",
    decree: false,
    img: "0",
  },
  {
    fullName: "Попович Ольга Васильевна",
    position: "Заместитель директора АУП",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Поскрякова Екатерина Юрьевна",
    position: "Заведующий ОССО",
    address: "Сколково",
    decree: false,
    img: "PoskryakovaEY.png",
  },
  {
    fullName: "Потапкина Ольга Валерьевна",
    position: "Специалист по работе с семьей",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Прохоров Сергей Валерьевич",
    position: "Специалист гражданской обороны",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Пудане Инесса Юровна",
    position: "Специалист по работе с семьей",
    address: "Интернациональная",
    decree: false,
    img: "PudaneIU.png",
  },
  {
    fullName: "Пунина Маргарита Витиславна",
    position: "Психолог в социальной сфере",
    address: "Раменки",
    decree: false,
    img: "PuninaMV.png",
  },
  {
    fullName: "Рубцова Мария Юрьевна",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: false,
    img: "0",
  },
  {
    fullName: "Савкина Елена Николаевна",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: true,
    img: "0",
  },
  {
    fullName: "Садыкова Елена Юрьевна",
    position: "Психолог в социальной сфере",
    address: "Раменки",
    decree: false,
    img: "SadikovaEU.png",
  },
  {
    fullName: "Салахова Светлана Сергеевна",
    position: "Специалист по работе с семьей",
    address: "Тропарево",
    decree: false,
    img: "SalahovaSS.png",
  },
  {
    fullName: "Саяпина Анастасия Юрьевна",
    position: "Специалист по работе с семьей",
    address: "Дорогомилово",
    decree: true,
    img: "0",
  },
  {
    fullName: "Селезнева Ольга Андреевна",
    position: "Заведующий ОКПСД",
    address: "Раменки",
    decree: false,
    img: "0",
  },
  {
    fullName: "Сергеева Златослава Игоревна",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: true,
    img: "0",
  },
  {
    fullName: "Семина Светлана Ивановна",
    position: "Специалист по работе с семьей",
    address: "Тропарево",
    decree: true,
    img: "0",
  },
  {
    fullName: "Сербиненко Юлия Сергеевна",
    position: "Психолог в социальной сфере",
    address: "Кунцево",
    decree: false,
    img: "SerbienkoYA.png",
  },
  {
    fullName: "Сидорова Марина Владимировна",
    position: "Психолог в социальной сфере",
    address: "Крылатское",
    decree: false,
    img: "SidorovaMV.png",
  },
  {
    fullName: "Сизикова Елена Владимировна",
    position: "Психолог в социальной сфере",
    address: "Дорогомилово",
    decree: false,
    img: "SizikovaEV.png",
  },
  {
    fullName: "Симченкова Галина Олеговна",
    position: "Специалист по работе с семьей",
    address: "Волынская",
    decree: true,
    img: "0",
  },
  {
    fullName: "Сироткина Светлана Витальевна",
    position: "Уборщик служебных помещений",
    address: "Раменки",
    decree: false,
    img: "0",
  },
  {
    fullName: "Соколова Татьяна Васильевна",
    position: "Психолог в социальной сфере",
    address: "Волынская",
    decree: false,
    img: "0",
  },
  {
    fullName: "Степанов Алексей Александрович",
    position: "Курьер",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Степанова Людмила Анатольевна",
    position: "Специалист по социальной работе",
    address: "Кунцево",
    decree: false,
    img: "StepanovaLA.png",
  },
  {
    fullName: "Сырейщикова Ярославна Сергеевна",
    position: "Медиатор в специализированной сфере",
    address: "Тропарево",
    decree: false,
    img: "0",
  },
  {
    fullName: "Таболина Александра Александровна",
    position: "Специалист по социальной работе",
    address: "Крылатское",
    decree: false,
    img: "0",
  },
  {
    fullName: "Тарасова Олеся Артуровна",
    position: "Специалист по работе с семьей",
    address: "Интернациональная",
    decree: false,
    img: "tarasovaoa.png",
  },
  {
    fullName: "Тимофеева Наталья Владимировна",
    position: "Специалист по социальной работе",
    address: "Тропарево",
    decree: false,
    img: "TimofeevaNV.png",
  },
  {
    fullName: "Тимошина Инна Васильевна",
    position: "Психолог в социальной сфере",
    address: "Крылатское",
    decree: false,
    img: "TimoshinaIV.png",
  },
  {
    fullName: "Ткаченко Людмила Константиновна",
    position: "Заведующий отделением ОКПСД",
    address: "Дорогомилово",
    decree: false,
    img: "TkachenkoLK.png",
  },
  {
    fullName: "Туполева Юлия Дмитриевна",
    position: "Психолог в социальной сфере",
    address: "Тропарево",
    decree: false,
    img: "TupolevaUD.png",
  },
  {
    fullName: "Тюренкова Елена Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: false,
    img: "TurenkovaEA.png",
  },
  {
    fullName: "Федоров Данила Андреевич",
    position: "Системный администратор",
    address: "Сколково",
    decree: false,
    img: "0",
  },
  {
    fullName: "Филатова Наталья Николаевна",
    position: "Заведующий хозяйством",
    address: "Раменки",
    decree: false,
    img: "0",
  },
  {
    fullName: "Флоринская Мария Александровна",
    position: "Заведующий филиалом",
    address: "Тропарево",
    decree: false,
    img: "FlorinskayaMA.png",
  },
  {
    fullName: "Хайдарова Любовь Николаевна",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: false,
    img: "HaidarovaLN.png",
  },
  {
    fullName: "Хатыкова Анна Витальевна",
    position: "Специалист по работе с семьей",
    address: "Волынская",
    decree: false,
    img: "0",
  },
  {
    fullName: "Хохлова Ирина Гавриловна",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: false,
    img: "HohlovaIG.png",
  },
  {
    fullName: "Хромова Татьяна Валерьевна",
    position: "Заведующий отделением ОКПСД",
    address: "Внуково",
    decree: false,
    img: "HromovoTV.png",
  },
  {
    fullName: "Хурумова Эка Павловна",
    position: "Специалист по социальной работе",
    address: "Сколково",
    decree: false,
    img: "HurumovaEP.png",
  },
  {
    fullName: "Чекмарёва Анна Вячеславовна",
    position: "Специалист по работе с семьей",
    address: "Солнцево",
    decree: true,
    img: "0",
  },
  {
    fullName: "Чумичева Мария Сергеевна",
    position: "Специалист по работе с семьей",
    address: "Интернациональная",
    decree: false,
    img: "chumichevams.png",
  },
  {
    fullName: "Шевченко Сергей Александрович",
    position: "Специалист по работе с семьей",
    address: "Кунцево",
    decree: false,
    img: "ShevchenkoSA.png",
  },
  {
    fullName: "Шеина Алина Алексеевна",
    position: "Специалист по работе с семьей",
    address: "Сколково",
    decree: false,
    img: "SheinaAA.png",
  },
  {
    fullName: "Широкалова Марина Александровна",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: false,
    img: "ShirokalovaMA.png",
  },
  {
    fullName: "Школдина Кира Александровна",
    position: "Заведующий ОКПСД",
    address: "Кунцево",
    decree: false,
    img: "ShkoldinaKA.png",
  },
  {
    fullName: "Яковлев Максим Александрович",
    position: "Специалист по социальной работе",
    address: "Раменки",
    decree: false,
    img: "YakovlevaMA.png",
  },
  {
    fullName: "Яковлева Наталья Евгеньевна",
    position: "Специалист по работе с семьей",
    address: "Раменки",
    decree: false,
    img: "YakovlevaNE.png",
  },
  {
    fullName: "Якунина Наталья Николаевна",
    position: "Специалист по работе с семьей",
    address: "Интернациональная",
    decree: false,
    img: "YakuninaNN.png",
  },
];

export default person
